version: "3.9"
services:
  nextjs:
    build: .
    container_name: nextjs-container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_DB_HOST: mysql
      NEXT_PUBLIC_DB_PORT: 3306
      NEXT_PUBLIC_DB_USER: root
      NEXT_PUBLIC_DB_PASSWORD: root
      NEXT_PUBLIC_DB_NAME: dashboard
      NEXT_PUBLIC_JWT_SECRET: 4f8a1e7b8f9c9d3e0b62c05fd3c7a2adce85a49d234b6f09d1
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
